//
//  Constants_Tags.m
//  ASIOS
//
//  Created by  Nick Pershin on 9/30/13.
//  Copyright (c) 2013  Nick Pershin. All rights reserved.
//
//  Ported from The Android Open Source Project
//  Copyright (C) 2008-2009 Marc Blank
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//


#import "Constants_Tags.h"

/**
 * The wbxml tags for EAS are all defined here.
 *
 * The extern int consts's, of the form <page>_<tag> = <constant> are used in parsing incoming
 * responses from the server (i.e. EasParser and its subclasses) and sending requests to the server
 */

@implementation Constants_Tags

// Wbxml page definitions for EAS
int const TAGS_AIRSYNC    = 0x00;
int const TAGS_CONTACTS   = 0x01;
int const TAGS_EMAIL      = 0x02;
int const TAGS_CALENDAR   = 0x04;
int const TAGS_MOVE       = 0x05;
int const TAGS_GIE        = 0x06;
int const TAGS_FOLDER     = 0x07;
int const TAGS_MREQ       = 0x08;
int const TAGS_TASK       = 0x09;
int const TAGS_CONTACTS2  = 0x0C;
int const TAGS_PING       = 0x0D;
int const TAGS_PROVISION  = 0x0E;
int const TAGS_SEARCH     = 0x0F;
int const TAGS_GAL        = 0x10;
int const TAGS_BASE       = 0x11;
int const TAGS_SETTINGS   = 0x12;
int const TAGS_DOCS       = 0x13;
int const TAGS_ITEMS      = 0x14;
// 14.0
int const TAGS_COMPOSE    = 0x15;
int const TAGS_EMAIL2     = 0x16;
// 14.1
int const TAGS_NOTES      = 0x17;
int const TAGS_RIGHTS     = 0x18;

// Shift applied to page numbers to generate tag
int const TAGS_PAGESHIFT = 6;


int const TAGS_SYNC_PAGE = 0 << TAGS_PAGESHIFT;
int const TAGS_SYNC_SYNC             = TAGS_SYNC_PAGE + 0x05;
int const TAGS_SYNC_RESPONSES        = TAGS_SYNC_PAGE + 0x06;
int const TAGS_SYNC_ADD              = TAGS_SYNC_PAGE + 0x07;
int const TAGS_SYNC_CHANGE           = TAGS_SYNC_PAGE + 0x08;
int const TAGS_SYNC_DELETE           = TAGS_SYNC_PAGE + 0x09;
int const TAGS_SYNC_FETCH            = TAGS_SYNC_PAGE + 0x0A;
int const TAGS_SYNC_SYNC_KEY         = TAGS_SYNC_PAGE + 0x0B;
int const TAGS_SYNC_CLIENT_ID        = TAGS_SYNC_PAGE + 0x0C;
int const TAGS_SYNC_SERVER_ID        = TAGS_SYNC_PAGE + 0x0D;
int const TAGS_SYNC_STATUS           = TAGS_SYNC_PAGE + 0x0E;
int const TAGS_SYNC_COLLECTION       = TAGS_SYNC_PAGE + 0x0F;
int const TAGS_SYNC_CLASS            = TAGS_SYNC_PAGE + 0x10;
int const TAGS_SYNC_VERSION          = TAGS_SYNC_PAGE + 0x11;
int const TAGS_SYNC_COLLECTION_ID    = TAGS_SYNC_PAGE + 0x12;
int const TAGS_SYNC_GET_CHANGES      = TAGS_SYNC_PAGE + 0x13;
int const TAGS_SYNC_MORE_AVAILABLE   = TAGS_SYNC_PAGE + 0x14;
int const TAGS_SYNC_WINDOW_SIZE      = TAGS_SYNC_PAGE + 0x15;
int const TAGS_SYNC_COMMANDS         = TAGS_SYNC_PAGE + 0x16;
int const TAGS_SYNC_OPTIONS          = TAGS_SYNC_PAGE + 0x17;
int const TAGS_SYNC_FILTER_TYPE      = TAGS_SYNC_PAGE + 0x18;
int const TAGS_SYNC_TRUNCATION       = TAGS_SYNC_PAGE + 0x19;
int const TAGS_SYNC_RTF_TRUNCATION   = TAGS_SYNC_PAGE + 0x1A;
int const TAGS_SYNC_CONFLICT         = TAGS_SYNC_PAGE + 0x1B;
int const TAGS_SYNC_COLLECTIONS      = TAGS_SYNC_PAGE + 0x1C;
int const TAGS_SYNC_APPLICATION_DATA = TAGS_SYNC_PAGE + 0x1D;
int const TAGS_SYNC_DELETES_AS_MOVES = TAGS_SYNC_PAGE + 0x1E;
int const TAGS_SYNC_NOTIFY_GUID      = TAGS_SYNC_PAGE + 0x1F;
int const TAGS_SYNC_SUPPORTED        = TAGS_SYNC_PAGE + 0x20;
int const TAGS_SYNC_SOFT_DELETE      = TAGS_SYNC_PAGE + 0x21;
int const TAGS_SYNC_MIME_SUPPORT     = TAGS_SYNC_PAGE + 0x22;
int const TAGS_SYNC_MIME_TRUNCATION  = TAGS_SYNC_PAGE + 0x23;
int const TAGS_SYNC_WAIT             = TAGS_SYNC_PAGE + 0x24;
int const TAGS_SYNC_LIMIT            = TAGS_SYNC_PAGE + 0x25;
int const TAGS_SYNC_PARTIAL          = TAGS_SYNC_PAGE + 0x26;


int const TAGS_GIE_PAGE = TAGS_GIE << TAGS_PAGESHIFT;
int const TAGS_GIE_GET_ITEM_ESTIMATE = TAGS_GIE_PAGE + 0x05;
int const TAGS_GIE_VERSION           = TAGS_GIE_PAGE + 0x06;
int const TAGS_GIE_COLLECTIONS       = TAGS_GIE_PAGE + 0x07;
int const TAGS_GIE_COLLECTION        = TAGS_GIE_PAGE + 0x08;
int const TAGS_GIE_CLASS             = TAGS_GIE_PAGE + 0x09;
int const TAGS_GIE_COLLECTION_ID     = TAGS_GIE_PAGE + 0x0A;
int const TAGS_GIE_DATE_TIME         = TAGS_GIE_PAGE + 0x0B;
int const TAGS_GIE_ESTIMATE          = TAGS_GIE_PAGE + 0x0C;
int const TAGS_GIE_RESPONSE          = TAGS_GIE_PAGE + 0x0D;
int const TAGS_GIE_STATUS            = TAGS_GIE_PAGE + 0x0E;


int const TAGS_CONTACTS_PAGE = TAGS_CONTACTS << TAGS_PAGESHIFT;
int const TAGS_CONTACTS_ANNIVERSARY                  = TAGS_CONTACTS_PAGE + 0x05;
int const TAGS_CONTACTS_ASSISTANT_NAME               = TAGS_CONTACTS_PAGE + 0x06;
int const TAGS_CONTACTS_ASSISTANT_TELEPHONE_NUMBER   = TAGS_CONTACTS_PAGE + 0x07;
int const TAGS_CONTACTS_BIRTHDAY                     = TAGS_CONTACTS_PAGE + 0x08;
int const TAGS_CONTACTS_BODY                         = TAGS_CONTACTS_PAGE + 0x09;
int const TAGS_CONTACTS_BODY_SIZE                    = TAGS_CONTACTS_PAGE + 0x0A;
int const TAGS_CONTACTS_BODY_TRUNCATED               = TAGS_CONTACTS_PAGE + 0x0B;
int const TAGS_CONTACTS_BUSINESS2_TELEPHONE_NUMBER   = TAGS_CONTACTS_PAGE + 0x0C;
int const TAGS_CONTACTS_BUSINESS_ADDRESS_CITY        = TAGS_CONTACTS_PAGE + 0x0D;
int const TAGS_CONTACTS_BUSINESS_ADDRESS_COUNTRY     = TAGS_CONTACTS_PAGE + 0x0E;
int const TAGS_CONTACTS_BUSINESS_ADDRESS_POSTAL_CODE = TAGS_CONTACTS_PAGE + 0x0F;
int const TAGS_CONTACTS_BUSINESS_ADDRESS_STATE       = TAGS_CONTACTS_PAGE + 0x10;
int const TAGS_CONTACTS_BUSINESS_ADDRESS_STREET      = TAGS_CONTACTS_PAGE + 0x11;
int const TAGS_CONTACTS_BUSINESS_FAX_NUMBER          = TAGS_CONTACTS_PAGE + 0x12;
int const TAGS_CONTACTS_BUSINESS_TELEPHONE_NUMBER    = TAGS_CONTACTS_PAGE + 0x13;
int const TAGS_CONTACTS_CAR_TELEPHONE_NUMBER         = TAGS_CONTACTS_PAGE + 0x14;
int const TAGS_CONTACTS_CATEGORIES                   = TAGS_CONTACTS_PAGE + 0x15;
int const TAGS_CONTACTS_CATEGORY                     = TAGS_CONTACTS_PAGE + 0x16;
int const TAGS_CONTACTS_CHILDREN                     = TAGS_CONTACTS_PAGE + 0x17;
int const TAGS_CONTACTS_CHILD                        = TAGS_CONTACTS_PAGE + 0x18;
int const TAGS_CONTACTS_COMPANY_NAME                 = TAGS_CONTACTS_PAGE + 0x19;
int const TAGS_CONTACTS_DEPARTMENT                   = TAGS_CONTACTS_PAGE + 0x1A;
int const TAGS_CONTACTS_EMAIL1_ADDRESS               = TAGS_CONTACTS_PAGE + 0x1B;
int const TAGS_CONTACTS_EMAIL2_ADDRESS               = TAGS_CONTACTS_PAGE + 0x1C;
int const TAGS_CONTACTS_EMAIL3_ADDRESS               = TAGS_CONTACTS_PAGE + 0x1D;
int const TAGS_CONTACTS_FILE_AS                      = TAGS_CONTACTS_PAGE + 0x1E;
int const TAGS_CONTACTS_FIRST_NAME                   = TAGS_CONTACTS_PAGE + 0x1F;
int const TAGS_CONTACTS_HOME2_TELEPHONE_NUMBER       = TAGS_CONTACTS_PAGE + 0x20;
int const TAGS_CONTACTS_HOME_ADDRESS_CITY            = TAGS_CONTACTS_PAGE + 0x21;
int const TAGS_CONTACTS_HOME_ADDRESS_COUNTRY         = TAGS_CONTACTS_PAGE + 0x22;
int const TAGS_CONTACTS_HOME_ADDRESS_POSTAL_CODE     = TAGS_CONTACTS_PAGE + 0x23;
int const TAGS_CONTACTS_HOME_ADDRESS_STATE           = TAGS_CONTACTS_PAGE + 0x24;
int const TAGS_CONTACTS_HOME_ADDRESS_STREET          = TAGS_CONTACTS_PAGE + 0x25;
int const TAGS_CONTACTS_HOME_FAX_NUMBER              = TAGS_CONTACTS_PAGE + 0x26;
int const TAGS_CONTACTS_HOME_TELEPHONE_NUMBER        = TAGS_CONTACTS_PAGE + 0x27;
int const TAGS_CONTACTS_JOB_TITLE                    = TAGS_CONTACTS_PAGE + 0x28;
int const TAGS_CONTACTS_LAST_NAME                    = TAGS_CONTACTS_PAGE + 0x29;
int const TAGS_CONTACTS_MIDDLE_NAME                  = TAGS_CONTACTS_PAGE + 0x2A;
int const TAGS_CONTACTS_MOBILE_TELEPHONE_NUMBER      = TAGS_CONTACTS_PAGE + 0x2B;
int const TAGS_CONTACTS_OFFICE_LOCATION              = TAGS_CONTACTS_PAGE + 0x2C;
int const TAGS_CONTACTS_OTHER_ADDRESS_CITY           = TAGS_CONTACTS_PAGE + 0x2D;
int const TAGS_CONTACTS_OTHER_ADDRESS_COUNTRY        = TAGS_CONTACTS_PAGE + 0x2E;
int const TAGS_CONTACTS_OTHER_ADDRESS_POSTAL_CODE    = TAGS_CONTACTS_PAGE + 0x2F;
int const TAGS_CONTACTS_OTHER_ADDRESS_STATE          = TAGS_CONTACTS_PAGE + 0x30;
int const TAGS_CONTACTS_OTHER_ADDRESS_STREET         = TAGS_CONTACTS_PAGE + 0x31;
int const TAGS_CONTACTS_PAGER_NUMBER                 = TAGS_CONTACTS_PAGE + 0x32;
int const TAGS_CONTACTS_RADIO_TELEPHONE_NUMBER       = TAGS_CONTACTS_PAGE + 0x33;
int const TAGS_CONTACTS_SPOUSE                       = TAGS_CONTACTS_PAGE + 0x34;
int const TAGS_CONTACTS_SUFFIX                       = TAGS_CONTACTS_PAGE + 0x35;
int const TAGS_CONTACTS_TITLE                        = TAGS_CONTACTS_PAGE + 0x36;
int const TAGS_CONTACTS_WEBPAGE                      = TAGS_CONTACTS_PAGE + 0x37;
int const TAGS_CONTACTS_YOMI_COMPANY_NAME            = TAGS_CONTACTS_PAGE + 0x38;
int const TAGS_CONTACTS_YOMI_FIRST_NAME              = TAGS_CONTACTS_PAGE + 0x39;
int const TAGS_CONTACTS_YOMI_LAST_NAME               = TAGS_CONTACTS_PAGE + 0x3A;
int const TAGS_CONTACTS_COMPRESSED_RTF               = TAGS_CONTACTS_PAGE + 0x3B;
int const TAGS_CONTACTS_PICTURE                      = TAGS_CONTACTS_PAGE + 0x3C;


int const TAGS_CALENDAR_PAGE = TAGS_CALENDAR << TAGS_PAGESHIFT;
int const TAGS_CALENDAR_TIME_ZONE                    = TAGS_CALENDAR_PAGE + 0x05;
int const TAGS_CALENDAR_ALL_DAY_EVENT                = TAGS_CALENDAR_PAGE + 0x06;
int const TAGS_CALENDAR_ATTENDEES                    = TAGS_CALENDAR_PAGE + 0x07;
int const TAGS_CALENDAR_ATTENDEE                     = TAGS_CALENDAR_PAGE + 0x08;
int const TAGS_CALENDAR_ATTENDEE_EMAIL               = TAGS_CALENDAR_PAGE + 0x09;
int const TAGS_CALENDAR_ATTENDEE_NAME                = TAGS_CALENDAR_PAGE + 0x0A;
int const TAGS_CALENDAR_BODY                         = TAGS_CALENDAR_PAGE + 0x0B;
int const TAGS_CALENDAR_BODY_TRUNCATED               = TAGS_CALENDAR_PAGE + 0x0C;
int const TAGS_CALENDAR_BUSY_STATUS                  = TAGS_CALENDAR_PAGE + 0x0D;
int const TAGS_CALENDAR_CATEGORIES                   = TAGS_CALENDAR_PAGE + 0x0E;
int const TAGS_CALENDAR_CATEGORY                     = TAGS_CALENDAR_PAGE + 0x0F;
int const TAGS_CALENDAR_COMPRESSED_RTF               = TAGS_CALENDAR_PAGE + 0x10;
int const TAGS_CALENDAR_DTSTAMP                      = TAGS_CALENDAR_PAGE + 0x11;
int const TAGS_CALENDAR_END_TIME                     = TAGS_CALENDAR_PAGE + 0x12;
int const TAGS_CALENDAR_EXCEPTION                    = TAGS_CALENDAR_PAGE + 0x13;
int const TAGS_CALENDAR_EXCEPTIONS                   = TAGS_CALENDAR_PAGE + 0x14;
int const TAGS_CALENDAR_EXCEPTION_IS_DELETED         = TAGS_CALENDAR_PAGE + 0x15;
int const TAGS_CALENDAR_EXCEPTION_START_TIME         = TAGS_CALENDAR_PAGE + 0x16;
int const TAGS_CALENDAR_LOCATION                     = TAGS_CALENDAR_PAGE + 0x17;
int const TAGS_CALENDAR_MEETING_STATUS               = TAGS_CALENDAR_PAGE + 0x18;
int const TAGS_CALENDAR_ORGANIZER_EMAIL              = TAGS_CALENDAR_PAGE + 0x19;
int const TAGS_CALENDAR_ORGANIZER_NAME               = TAGS_CALENDAR_PAGE + 0x1A;
int const TAGS_CALENDAR_RECURRENCE                   = TAGS_CALENDAR_PAGE + 0x1B;
int const TAGS_CALENDAR_RECURRENCE_TYPE              = TAGS_CALENDAR_PAGE + 0x1C;
int const TAGS_CALENDAR_RECURRENCE_UNTIL             = TAGS_CALENDAR_PAGE + 0x1D;
int const TAGS_CALENDAR_RECURRENCE_OCCURRENCES       = TAGS_CALENDAR_PAGE + 0x1E;
int const TAGS_CALENDAR_RECURRENCE_INTERVAL          = TAGS_CALENDAR_PAGE + 0x1F;
int const TAGS_CALENDAR_RECURRENCE_DAYOFWEEK         = TAGS_CALENDAR_PAGE + 0x20;
int const TAGS_CALENDAR_RECURRENCE_DAYOFMONTH        = TAGS_CALENDAR_PAGE + 0x21;
int const TAGS_CALENDAR_RECURRENCE_WEEKOFMONTH       = TAGS_CALENDAR_PAGE + 0x22;
int const TAGS_CALENDAR_RECURRENCE_MONTHOFYEAR       = TAGS_CALENDAR_PAGE + 0x23;
int const TAGS_CALENDAR_REMINDER_MINS_BEFORE         = TAGS_CALENDAR_PAGE + 0x24;
int const TAGS_CALENDAR_SENSITIVITY                  = TAGS_CALENDAR_PAGE + 0x25;
int const TAGS_CALENDAR_SUBJECT                      = TAGS_CALENDAR_PAGE + 0x26;
int const TAGS_CALENDAR_START_TIME                   = TAGS_CALENDAR_PAGE + 0x27;
int const TAGS_CALENDAR_UID                          = TAGS_CALENDAR_PAGE + 0x28;
int const TAGS_CALENDAR_ATTENDEE_STATUS              = TAGS_CALENDAR_PAGE + 0x29;
int const TAGS_CALENDAR_ATTENDEE_TYPE                = TAGS_CALENDAR_PAGE + 0x2A;
int const TAGS_CALENDAR_ATTACHMENT                   = TAGS_CALENDAR_PAGE + 0x2B;
int const TAGS_CALENDAR_ATTACHMENTS                  = TAGS_CALENDAR_PAGE + 0x2C;
int const TAGS_CALENDAR_ATT_NAME                     = TAGS_CALENDAR_PAGE + 0x2D;
int const TAGS_CALENDAR_ATT_SIZE                     = TAGS_CALENDAR_PAGE + 0x2E;
int const TAGS_CALENDAR_ATT_OID                      = TAGS_CALENDAR_PAGE + 0x2F;
int const TAGS_CALENDAR_ATT_METHOD                   = TAGS_CALENDAR_PAGE + 0x30;
int const TAGS_CALENDAR_ATT_REMOVED                  = TAGS_CALENDAR_PAGE + 0x31;
int const TAGS_CALENDAR_DISPLAY_NAME                 = TAGS_CALENDAR_PAGE + 0x32;
int const TAGS_CALENDAR_DISALLOW_NEW_TIME_PROPOSAL   = TAGS_CALENDAR_PAGE + 0x33;
int const TAGS_CALENDAR_RESPONSE_REQUESTED           = TAGS_CALENDAR_PAGE + 0x34;
int const TAGS_CALENDAR_APPOINTMENT_REPLY_TIME       = TAGS_CALENDAR_PAGE + 0x35;
int const TAGS_CALENDAR_RESPONSE_TYPE                = TAGS_CALENDAR_PAGE + 0x36;
int const TAGS_CALENDAR_CALENDAR_TYPE                = TAGS_CALENDAR_PAGE + 0x37;
int const TAGS_CALENDAR_IS_LEAP_MONTH                = TAGS_CALENDAR_PAGE + 0x38;
int const TAGS_CALENDAR_FIRST_DAY_OF_WEEK            = TAGS_CALENDAR_PAGE + 0x39;
int const TAGS_CALENDAR_ONLINE_MEETING_CONFLINK      = TAGS_CALENDAR_PAGE + 0x3A;
int const TAGS_CALENDAR_ONLINE_MEETING_EXTERNAL_LINK = TAGS_CALENDAR_PAGE + 0x3B;


int const TAGS_FOLDER_PAGE = TAGS_FOLDER << TAGS_PAGESHIFT;
int const TAGS_FOLDER_FOLDERS       = TAGS_FOLDER_PAGE + 0x05;
int const TAGS_FOLDER_FOLDER        = TAGS_FOLDER_PAGE + 0x06;
int const TAGS_FOLDER_DISPLAY_NAME  = TAGS_FOLDER_PAGE + 0x07;
int const TAGS_FOLDER_SERVER_ID     = TAGS_FOLDER_PAGE + 0x08;
int const TAGS_FOLDER_PARENT_ID     = TAGS_FOLDER_PAGE + 0x09;
int const TAGS_FOLDER_TYPE          = TAGS_FOLDER_PAGE + 0x0A;
int const TAGS_FOLDER_RESPONSE      = TAGS_FOLDER_PAGE + 0x0B;
int const TAGS_FOLDER_STATUS        = TAGS_FOLDER_PAGE + 0x0C;
int const TAGS_FOLDER_CONTENT_CLASS = TAGS_FOLDER_PAGE + 0x0D;
int const TAGS_FOLDER_CHANGES       = TAGS_FOLDER_PAGE + 0x0E;
int const TAGS_FOLDER_ADD           = TAGS_FOLDER_PAGE + 0x0F;
int const TAGS_FOLDER_DELETE        = TAGS_FOLDER_PAGE + 0x10;
int const TAGS_FOLDER_UPDATE        = TAGS_FOLDER_PAGE + 0x11;
int const TAGS_FOLDER_SYNC_KEY      = TAGS_FOLDER_PAGE + 0x12;
int const TAGS_FOLDER_FOLDER_CREATE = TAGS_FOLDER_PAGE + 0x13;
int const TAGS_FOLDER_FOLDER_DELETE = TAGS_FOLDER_PAGE + 0x14;
int const TAGS_FOLDER_FOLDER_UPDATE = TAGS_FOLDER_PAGE + 0x15;
int const TAGS_FOLDER_FOLDER_SYNC   = TAGS_FOLDER_PAGE + 0x16;
int const TAGS_FOLDER_COUNT         = TAGS_FOLDER_PAGE + 0x17;
int const TAGS_FOLDER_VERSION       = TAGS_FOLDER_PAGE + 0x18;


int const TAGS_MREQ_PAGE = TAGS_MREQ << TAGS_PAGESHIFT;
int const TAGS_MREQ_CAL_ID           = TAGS_MREQ_PAGE + 0x05;
int const TAGS_MREQ_COLLECTION_ID    = TAGS_MREQ_PAGE + 0x06;
int const TAGS_MREQ_MEETING_RESPONSE = TAGS_MREQ_PAGE + 0x07;
int const TAGS_MREQ_REQ_ID           = TAGS_MREQ_PAGE + 0x08;
int const TAGS_MREQ_REQUEST          = TAGS_MREQ_PAGE + 0x09;
int const TAGS_MREQ_RESULT           = TAGS_MREQ_PAGE + 0x0A;
int const TAGS_MREQ_STATUS           = TAGS_MREQ_PAGE + 0x0B;
int const TAGS_MREQ_USER_RESPONSE    = TAGS_MREQ_PAGE + 0x0C;
int const TAGS_MREQ_VERSION          = TAGS_MREQ_PAGE + 0x0D;


int const TAGS_EMAIL_PAGE = TAGS_EMAIL << TAGS_PAGESHIFT;
int const TAGS_EMAIL_ATTACHMENT                 = TAGS_EMAIL_PAGE + 0x05;
int const TAGS_EMAIL_ATTACHMENTS                = TAGS_EMAIL_PAGE + 0x06;
int const TAGS_EMAIL_ATT_NAME                   = TAGS_EMAIL_PAGE + 0x07;
int const TAGS_EMAIL_ATT_SIZE                   = TAGS_EMAIL_PAGE + 0x08;
int const TAGS_EMAIL_ATT0ID                     = TAGS_EMAIL_PAGE + 0x09;
int const TAGS_EMAIL_ATT_METHOD                 = TAGS_EMAIL_PAGE + 0x0A;
int const TAGS_EMAIL_ATT_REMOVED                = TAGS_EMAIL_PAGE + 0x0B;
int const TAGS_EMAIL_BODY                       = TAGS_EMAIL_PAGE + 0x0C;
int const TAGS_EMAIL_BODY_SIZE                  = TAGS_EMAIL_PAGE + 0x0D;
int const TAGS_EMAIL_BODY_TRUNCATED             = TAGS_EMAIL_PAGE + 0x0E;
int const TAGS_EMAIL_DATE_RECEIVED              = TAGS_EMAIL_PAGE + 0x0F;
int const TAGS_EMAIL_DISPLAY_NAME               = TAGS_EMAIL_PAGE + 0x10;
int const TAGS_EMAIL_DISPLAY_TO                 = TAGS_EMAIL_PAGE + 0x11;
int const TAGS_EMAIL_IMPORTANCE                 = TAGS_EMAIL_PAGE + 0x12;
int const TAGS_EMAIL_MESSAGE_CLASS              = TAGS_EMAIL_PAGE + 0x13;
int const TAGS_EMAIL_SUBJECT                    = TAGS_EMAIL_PAGE + 0x14;
int const TAGS_EMAIL_READ                       = TAGS_EMAIL_PAGE + 0x15;
int const TAGS_EMAIL_TO                         = TAGS_EMAIL_PAGE + 0x16;
int const TAGS_EMAIL_CC                         = TAGS_EMAIL_PAGE + 0x17;
int const TAGS_EMAIL_FROM                       = TAGS_EMAIL_PAGE + 0x18;
int const TAGS_EMAIL_REPLY_TO                   = TAGS_EMAIL_PAGE + 0x19;
int const TAGS_EMAIL_ALL_DAY_EVENT              = TAGS_EMAIL_PAGE + 0x1A;
int const TAGS_EMAIL_CATEGORIES                 = TAGS_EMAIL_PAGE + 0x1B;
int const TAGS_EMAIL_CATEGORY                   = TAGS_EMAIL_PAGE + 0x1C;
int const TAGS_EMAIL_DTSTAMP                    = TAGS_EMAIL_PAGE + 0x1D;
int const TAGS_EMAIL_END_TIME                   = TAGS_EMAIL_PAGE + 0x1E;
int const TAGS_EMAIL_INSTANCE_TYPE              = TAGS_EMAIL_PAGE + 0x1F;
int const TAGS_EMAIL_INTD_BUSY_STATUS           = TAGS_EMAIL_PAGE + 0x20;
int const TAGS_EMAIL_LOCATION                   = TAGS_EMAIL_PAGE + 0x21;
int const TAGS_EMAIL_MEETING_REQUEST            = TAGS_EMAIL_PAGE + 0x22;
int const TAGS_EMAIL_ORGANIZER                  = TAGS_EMAIL_PAGE + 0x23;
int const TAGS_EMAIL_RECURRENCE_ID              = TAGS_EMAIL_PAGE + 0x24;
int const TAGS_EMAIL_REMINDER                   = TAGS_EMAIL_PAGE + 0x25;
int const TAGS_EMAIL_RESPONSE_REQUESTED         = TAGS_EMAIL_PAGE + 0x26;
int const TAGS_EMAIL_RECURRENCES                = TAGS_EMAIL_PAGE + 0x27;
int const TAGS_EMAIL_RECURRENCE                 = TAGS_EMAIL_PAGE + 0x28;
int const TAGS_EMAIL_RECURRENCE_TYPE            = TAGS_EMAIL_PAGE + 0x29;
int const TAGS_EMAIL_RECURRENCE_UNTIL           = TAGS_EMAIL_PAGE + 0x2A;
int const TAGS_EMAIL_RECURRENCE_OCCURRENCES     = TAGS_EMAIL_PAGE + 0x2B;
int const TAGS_EMAIL_RECURRENCE_INTERVAL        = TAGS_EMAIL_PAGE + 0x2C;
int const TAGS_EMAIL_RECURRENCE_DAYOFWEEK       = TAGS_EMAIL_PAGE + 0x2D;
int const TAGS_EMAIL_RECURRENCE_DAYOFMONTH      = TAGS_EMAIL_PAGE + 0x2E;
int const TAGS_EMAIL_RECURRENCE_WEEKOFMONTH     = TAGS_EMAIL_PAGE + 0x2F;
int const TAGS_EMAIL_RECURRENCE_MONTHOFYEAR     = TAGS_EMAIL_PAGE + 0x30;
int const TAGS_EMAIL_START_TIME                 = TAGS_EMAIL_PAGE + 0x31;
int const TAGS_EMAIL_SENSITIVITY                = TAGS_EMAIL_PAGE + 0x32;
int const TAGS_EMAIL_TIME_ZONE                  = TAGS_EMAIL_PAGE + 0x33;
int const TAGS_EMAIL_GLOBAL_OBJID               = TAGS_EMAIL_PAGE + 0x34;
int const TAGS_EMAIL_THREAD_TOPIC               = TAGS_EMAIL_PAGE + 0x35;
int const TAGS_EMAIL_MIME_DATA                  = TAGS_EMAIL_PAGE + 0x36;
int const TAGS_EMAIL_MIME_TRUNCATED             = TAGS_EMAIL_PAGE + 0x37;
int const TAGS_EMAIL_MIME_SIZE                  = TAGS_EMAIL_PAGE + 0x38;
int const TAGS_EMAIL_INTERNET_CPID              = TAGS_EMAIL_PAGE + 0x39;
int const TAGS_EMAIL_FLAG                       = TAGS_EMAIL_PAGE + 0x3A;
int const TAGS_EMAIL_FLAG_STATUS                = TAGS_EMAIL_PAGE + 0x3B;
int const TAGS_EMAIL_CONTENT_CLASS              = TAGS_EMAIL_PAGE + 0x3C;
int const TAGS_EMAIL_FLAG_TYPE                  = TAGS_EMAIL_PAGE + 0x3D;
int const TAGS_EMAIL_COMPLETE_TIME              = TAGS_EMAIL_PAGE + 0x3E;
int const TAGS_EMAIL_DISALLOW_NEW_TIME_PROPOSAL = TAGS_EMAIL_PAGE + 0x3F;


int const TAGS_TASK_PAGE = TAGS_TASK << TAGS_PAGESHIFT;
int const TAGS_TASK_BODY                     = TAGS_TASK_PAGE + 0x05;
int const TAGS_TASK_BODY_SIZE                = TAGS_TASK_PAGE + 0x06;
int const TAGS_TASK_BODY_TRUNCATED           = TAGS_TASK_PAGE + 0x07;
int const TAGS_TASK_CATEGORIES               = TAGS_TASK_PAGE + 0x08;
int const TAGS_TASK_CATEGORY                 = TAGS_TASK_PAGE + 0x09;
int const TAGS_TASK_COMPLETE                 = TAGS_TASK_PAGE + 0x0A;
int const TAGS_TASK_DATE_COMPLETED           = TAGS_TASK_PAGE + 0x0B;
int const TAGS_TASK_DUE_DATE                 = TAGS_TASK_PAGE + 0x0C;
int const TAGS_TASK_UTC_DUE_DATE             = TAGS_TASK_PAGE + 0x0D;
int const TAGS_TASK_IMPORTANCE               = TAGS_TASK_PAGE + 0x0E;
int const TAGS_TASK_RECURRENCE               = TAGS_TASK_PAGE + 0x0F;
int const TAGS_TASK_RECURRENCE_TYPE          = TAGS_TASK_PAGE + 0x10;
int const TAGS_TASK_RECURRENCE_START         = TAGS_TASK_PAGE + 0x11;
int const TAGS_TASK_RECURRENCE_UNTIL         = TAGS_TASK_PAGE + 0x12;
int const TAGS_TASK_RECURRENCE_OCCURRENCES   = TAGS_TASK_PAGE + 0x13;
int const TAGS_TASK_RECURRENCE_INTERVAL      = TAGS_TASK_PAGE + 0x14;
int const TAGS_TASK_RECURRENCE_DAY_OF_MONTH  = TAGS_TASK_PAGE + 0x15;
int const TAGS_TASK_RECURRENCE_DAY_OF_WEEK   = TAGS_TASK_PAGE + 0x16;
int const TAGS_TASK_RECURRENCE_WEEK_OF_MONTH = TAGS_TASK_PAGE + 0x17;
int const TAGS_TASK_RECURRENCE_MONTH_OF_YEAR = TAGS_TASK_PAGE + 0x18;
int const TAGS_TASK_RECURRENCE_REGENERATE    = TAGS_TASK_PAGE + 0x19;
int const TAGS_TASK_RECURRENCE_DEAD_OCCUR    = TAGS_TASK_PAGE + 0x1A;
int const TAGS_TASK_REMINDER_SET             = TAGS_TASK_PAGE + 0x1B;
int const TAGS_TASK_REMINDER_TIME            = TAGS_TASK_PAGE + 0x1C;
int const TAGS_TASK_SENSITIVITY              = TAGS_TASK_PAGE + 0x1D;
int const TAGS_TASK_START_DATE               = TAGS_TASK_PAGE + 0x1E;
int const TAGS_TASK_UTC_START_DATE           = TAGS_TASK_PAGE + 0x1F;
int const TAGS_TASK_SUBJECT                  = TAGS_TASK_PAGE + 0x20;
int const TAGS_COMPRESSED_RTF                = TAGS_TASK_PAGE + 0x21;
int const TAGS_ORDINAL_DATE                  = TAGS_TASK_PAGE + 0x22;
int const TAGS_SUBORDINAL_DATE               = TAGS_TASK_PAGE + 0x23;


int const TAGS_MOVE_PAGE = TAGS_MOVE << TAGS_PAGESHIFT;
int const TAGS_MOVE_MOVE_ITEMS  = TAGS_MOVE_PAGE + 0x05;
int const TAGS_MOVE_MOVE        = TAGS_MOVE_PAGE + 0x06;
int const TAGS_MOVE_SRCMSGID    = TAGS_MOVE_PAGE + 0x07;
int const TAGS_MOVE_SRCFLDID    = TAGS_MOVE_PAGE + 0x08;
int const TAGS_MOVE_DSTFLDID    = TAGS_MOVE_PAGE + 0x09;
int const TAGS_MOVE_RESPONSE    = TAGS_MOVE_PAGE + 0x0A;
int const TAGS_MOVE_STATUS      = TAGS_MOVE_PAGE + 0x0B;
int const TAGS_MOVE_DSTMSGID    = TAGS_MOVE_PAGE + 0x0C;


int const TAGS_CONTACTS2_PAGE = TAGS_CONTACTS2 << TAGS_PAGESHIFT;
int const TAGS_CONTACTS2_CUSTOMER_ID        = TAGS_CONTACTS2_PAGE + 0x05;
int const TAGS_CONTACTS2_GOVERNMENT_ID      = TAGS_CONTACTS2_PAGE + 0x06;
int const TAGS_CONTACTS2_IM_ADDRESS         = TAGS_CONTACTS2_PAGE + 0x07;
int const TAGS_CONTACTS2_IM_ADDRESS_2       = TAGS_CONTACTS2_PAGE + 0x08;
int const TAGS_CONTACTS2_IM_ADDRESS_3       = TAGS_CONTACTS2_PAGE + 0x09;
int const TAGS_CONTACTS2_MANAGER_NAME       = TAGS_CONTACTS2_PAGE + 0x0A;
int const TAGS_CONTACTS2_COMPANY_MAIN_PHONE = TAGS_CONTACTS2_PAGE + 0x0B;
int const TAGS_CONTACTS2_ACCOUNT_NAME       = TAGS_CONTACTS2_PAGE + 0x0C;
int const TAGS_CONTACTS2_NICKNAME           = TAGS_CONTACTS2_PAGE + 0x0D;
int const TAGS_CONTACTS2_MMS                = TAGS_CONTACTS2_PAGE + 0x0E;


int const TAGS_PING_PAGE = TAGS_PING << TAGS_PAGESHIFT;
int const TAGS_PING_PING                = TAGS_PING_PAGE + 0x05;
int const TAGS_PING_AUTD_STATE          = TAGS_PING_PAGE + 0x06;
int const TAGS_PING_STATUS              = TAGS_PING_PAGE + 0x07;
int const TAGS_PING_HEARTBEAT_INTERVAL  = TAGS_PING_PAGE + 0x08;
int const TAGS_PING_FOLDERS             = TAGS_PING_PAGE + 0x09;
int const TAGS_PING_FOLDER              = TAGS_PING_PAGE + 0x0A;
int const TAGS_PING_ID                  = TAGS_PING_PAGE + 0x0B;
int const TAGS_PING_CLASS               = TAGS_PING_PAGE + 0x0C;
int const TAGS_PING_MAX_FOLDERS         = TAGS_PING_PAGE + 0x0D;


int const TAGS_SEARCH_PAGE = TAGS_SEARCH << TAGS_PAGESHIFT;
int const TAGS_SEARCH_SEARCH            = TAGS_SEARCH_PAGE + 0x05;
int const TAGS_SEARCH_STORES            = TAGS_SEARCH_PAGE + 0x06;
int const TAGS_SEARCH_STORE             = TAGS_SEARCH_PAGE + 0x07;
int const TAGS_SEARCH_NAME              = TAGS_SEARCH_PAGE + 0x08;
int const TAGS_SEARCH_QUERY             = TAGS_SEARCH_PAGE + 0x09;
int const TAGS_SEARCH_OPTIONS           = TAGS_SEARCH_PAGE + 0x0A;
int const TAGS_SEARCH_RANGE             = TAGS_SEARCH_PAGE + 0x0B;
int const TAGS_SEARCH_STATUS            = TAGS_SEARCH_PAGE + 0x0C;
int const TAGS_SEARCH_RESPONSE          = TAGS_SEARCH_PAGE + 0x0D;
int const TAGS_SEARCH_RESULT            = TAGS_SEARCH_PAGE + 0x0E;
int const TAGS_SEARCH_PROPERTIES        = TAGS_SEARCH_PAGE + 0x0F;
int const TAGS_SEARCH_TOTAL             = TAGS_SEARCH_PAGE + 0x10;
int const TAGS_SEARCH_EQUAL_TO          = TAGS_SEARCH_PAGE + 0x11;
int const TAGS_SEARCH_VALUE             = TAGS_SEARCH_PAGE + 0x12;
int const TAGS_SEARCH_AND               = TAGS_SEARCH_PAGE + 0x13;
int const TAGS_SEARCH_OR                = TAGS_SEARCH_PAGE + 0x14;
int const TAGS_SEARCH_FREE_TEXT         = TAGS_SEARCH_PAGE + 0x15;
int const TAGS_SEARCH_SUBSTRING_OP      = TAGS_SEARCH_PAGE + 0x16;
int const TAGS_SEARCH_DEEP_TRAVERSAL    = TAGS_SEARCH_PAGE + 0x17;
int const TAGS_SEARCH_LONG_ID           = TAGS_SEARCH_PAGE + 0x18;
int const TAGS_SEARCH_REBUILD_RESULTS   = TAGS_SEARCH_PAGE + 0x19;
int const TAGS_SEARCH_LESS_THAN         = TAGS_SEARCH_PAGE + 0x1A;
int const TAGS_SEARCH_GREATER_THAN      = TAGS_SEARCH_PAGE + 0x1B;
int const TAGS_SEARCH_SCHEMA            = TAGS_SEARCH_PAGE + 0x1C;
int const TAGS_SEARCH_SUPPORTED         = TAGS_SEARCH_PAGE + 0x1D;
int const TAGS_SEARCH_USER_NAME         = TAGS_SEARCH_PAGE + 0x1E;
int const TAGS_SEARCH_PASSWORD          = TAGS_SEARCH_PAGE + 0x1F;
int const TAGS_SEARCH_CONVERSATION_ID   = TAGS_SEARCH_PAGE + 0x20;
// The following tags are supported in MS-AS 14.1 and above
int const TAGS_SEARCH_PICTURE           = TAGS_SEARCH_PAGE + 0x21;
int const TAGS_SEARCH_MAX_SIZE          = TAGS_SEARCH_PAGE + 0x22;
int const TAGS_SEARCH_MAX_PICTURES      = TAGS_SEARCH_PAGE + 0x23;


int const TAGS_GAL_PAGE = TAGS_GAL << TAGS_PAGESHIFT;
int const TAGS_GAL_DISPLAY_NAME = TAGS_GAL_PAGE + 0x05;
int const TAGS_GAL_PHONE        = TAGS_GAL_PAGE + 0x06;
int const TAGS_GAL_OFFICE       = TAGS_GAL_PAGE + 0x07;
int const TAGS_GAL_TITLE        = TAGS_GAL_PAGE + 0x08;
int const TAGS_GAL_COMPANY      = TAGS_GAL_PAGE + 0x09;
int const TAGS_GAL_ALIAS        = TAGS_GAL_PAGE + 0x0A;
int const TAGS_GAL_FIRST_NAME   = TAGS_GAL_PAGE + 0x0B;
int const TAGS_GAL_LAST_NAME    = TAGS_GAL_PAGE + 0x0C;
int const TAGS_GAL_HOME_PHONE   = TAGS_GAL_PAGE + 0x0D;
int const TAGS_GAL_MOBILE_PHONE = TAGS_GAL_PAGE + 0x0E;
int const TAGS_GAL_EMAIL_ADDRESS = TAGS_GAL_PAGE + 0x0F;
// The following tags are supported in MS-AS 14.1 and above
int const TAGS_GAL_PICTURE      = TAGS_GAL_PAGE + 0x10;
int const TAGS_GAL_STATUS       = TAGS_GAL_PAGE + 0x11;
int const TAGS_GAL_DATA         = TAGS_GAL_PAGE + 0x12;


int const TAGS_PROVISION_PAGE = TAGS_PROVISION << TAGS_PAGESHIFT;
// EAS 2.5
int const TAGS_PROVISION_PROVISION   = TAGS_PROVISION_PAGE + 0x05;
int const TAGS_PROVISION_POLICIES    = TAGS_PROVISION_PAGE + 0x06;
int const TAGS_PROVISION_POLICY      = TAGS_PROVISION_PAGE + 0x07;
int const TAGS_PROVISION_POLICY_TYPE = TAGS_PROVISION_PAGE + 0x08;
int const TAGS_PROVISION_POLICY_KEY  = TAGS_PROVISION_PAGE + 0x09;
int const TAGS_PROVISION_DATA        = TAGS_PROVISION_PAGE + 0x0A;
int const TAGS_PROVISION_STATUS      = TAGS_PROVISION_PAGE + 0x0B;
int const TAGS_PROVISION_REMOTE_WIPE = TAGS_PROVISION_PAGE + 0x0C;
// EAS 12.0
int const TAGS_PROVISION_EAS_PROVISION_DOC                   = TAGS_PROVISION_PAGE + 0x0D;
int const TAGS_PROVISION_DEVICE_PASSWORD_ENABLED             = TAGS_PROVISION_PAGE + 0x0E;
int const TAGS_PROVISION_ALPHA_DEVICE_PASSWORD_ENABLED       = TAGS_PROVISION_PAGE + 0x0F;
int const TAGS_PROVISION_DEVICE_ENCRYPTION_ENABLED           = TAGS_PROVISION_PAGE + 0x10;
int const TAGS_PROVISION_PASSWORD_RECOVERY_ENABLED           = TAGS_PROVISION_PAGE + 0x11;
int const TAGS_PROVISION_ATTACHMENTS_ENABLED                 = TAGS_PROVISION_PAGE + 0x13;
int const TAGS_PROVISION_MIN_DEVICE_PASSWORD_LENGTH          = TAGS_PROVISION_PAGE + 0x14;
int const TAGS_PROVISION_MAX_INACTIVITY_TIME_DEVICE_LOCK     = TAGS_PROVISION_PAGE + 0x15;
int const TAGS_PROVISION_MAX_DEVICE_PASSWORD_FAILED_ATTEMPTS = TAGS_PROVISION_PAGE + 0x16;
int const TAGS_PROVISION_MAX_ATTACHMENT_SIZE                 = TAGS_PROVISION_PAGE + 0x17;
int const TAGS_PROVISION_ALLOW_SIMPLE_DEVICE_PASSWORD        = TAGS_PROVISION_PAGE + 0x18;
int const TAGS_PROVISION_DEVICE_PASSWORD_EXPIRATION          = TAGS_PROVISION_PAGE + 0x19;
int const TAGS_PROVISION_DEVICE_PASSWORD_HISTORY             = TAGS_PROVISION_PAGE + 0x1A;
int const TAGS_PROVISION_MAX_SUPPORTED_TAG                   =  TAGS_PROVISION_DEVICE_PASSWORD_HISTORY;
// EAS 12.1
int const TAGS_PROVISION_ALLOW_STORAGE_CARD                     = TAGS_PROVISION_PAGE + 0x1B;
int const TAGS_PROVISION_ALLOW_CAMERA                           = TAGS_PROVISION_PAGE + 0x1C;
int const TAGS_PROVISION_REQUIRE_DEVICE_ENCRYPTION              = TAGS_PROVISION_PAGE + 0x1D;
int const TAGS_PROVISION_ALLOW_UNSIGNED_APPLICATIONS            = TAGS_PROVISION_PAGE + 0x1E;
int const TAGS_PROVISION_ALLOW_UNSIGNED_INSTALLATION_PACKAGES   = TAGS_PROVISION_PAGE + 0x1F;
int const TAGS_PROVISION_MIN_DEVICE_PASSWORD_COMPLEX_CHARS      = TAGS_PROVISION_PAGE + 0x20;
int const TAGS_PROVISION_ALLOW_WIFI                             = TAGS_PROVISION_PAGE + 0x21;
int const TAGS_PROVISION_ALLOW_TEXT_MESSAGING                   = TAGS_PROVISION_PAGE + 0x22;
int const TAGS_PROVISION_ALLOW_POP_IMAP_EMAIL                   = TAGS_PROVISION_PAGE + 0x23;
int const TAGS_PROVISION_ALLOW_BLUETOOTH                        = TAGS_PROVISION_PAGE + 0x24;
int const TAGS_PROVISION_ALLOW_IRDA                             = TAGS_PROVISION_PAGE + 0x25;
int const TAGS_PROVISION_REQUIRE_MANUAL_SYNC_WHEN_ROAMING       = TAGS_PROVISION_PAGE + 0x26;
int const TAGS_PROVISION_ALLOW_DESKTOP_SYNC                     = TAGS_PROVISION_PAGE + 0x27;
int const TAGS_PROVISION_MAX_CALENDAR_AGE_FILTER                = TAGS_PROVISION_PAGE + 0x28;
int const TAGS_PROVISION_ALLOW_HTML_EMAIL                       = TAGS_PROVISION_PAGE + 0x29;
int const TAGS_PROVISION_MAX_EMAIL_AGE_FILTER                   = TAGS_PROVISION_PAGE + 0x2A;
int const TAGS_PROVISION_MAX_EMAIL_BODY_TRUNCATION_SIZE         = TAGS_PROVISION_PAGE + 0x2B;
int const TAGS_PROVISION_MAX_EMAIL_HTML_BODY_TRUNCATION_SIZE    = TAGS_PROVISION_PAGE + 0x2C;
int const TAGS_PROVISION_REQUIRE_SIGNED_SMIME_MESSAGES          = TAGS_PROVISION_PAGE + 0x2D;
int const TAGS_PROVISION_REQUIRE_ENCRYPTED_SMIME_MESSAGES       = TAGS_PROVISION_PAGE + 0x2E;
int const TAGS_PROVISION_REQUIRE_SIGNED_SMIME_ALGORITHM         = TAGS_PROVISION_PAGE + 0x2F;
int const TAGS_PROVISION_REQUIRE_ENCRYPTION_SMIME_ALGORITHM     = TAGS_PROVISION_PAGE + 0x30;
int const TAGS_PROVISION_ALLOW_SMIME_ENCRYPTION_NEGOTIATION     = TAGS_PROVISION_PAGE + 0x31;
int const TAGS_PROVISION_ALLOW_SMIME_SOFT_CERTS                 = TAGS_PROVISION_PAGE + 0x32;
int const TAGS_PROVISION_ALLOW_BROWSER                          = TAGS_PROVISION_PAGE + 0x33;
int const TAGS_PROVISION_ALLOW_CONSUMER_EMAIL                   = TAGS_PROVISION_PAGE + 0x34;
int const TAGS_PROVISION_ALLOW_REMOTE_DESKTOP                   = TAGS_PROVISION_PAGE + 0x35;
int const TAGS_PROVISION_ALLOW_INTERNET_SHARING                 = TAGS_PROVISION_PAGE + 0x36;
int const TAGS_PROVISION_UNAPPROVED_IN_ROM_APPLICATION_LIST     = TAGS_PROVISION_PAGE + 0x37;
int const TAGS_PROVISION_APPLICATION_NAME                       = TAGS_PROVISION_PAGE + 0x38;
int const TAGS_PROVISION_APPROVED_APPLICATION_LIST              = TAGS_PROVISION_PAGE + 0x39;
int const TAGS_PROVISION_HASH                                   = TAGS_PROVISION_PAGE + 0x3A;

int const TAGS_BASE_PAGE = TAGS_BASE << TAGS_PAGESHIFT;
int const TAGS_BASE_BODY_PREFERENCE     = TAGS_BASE_PAGE + 0x05;
int const TAGS_BASE_TYPE                = TAGS_BASE_PAGE + 0x06;
int const TAGS_BASE_TRUNCATION_SIZE     = TAGS_BASE_PAGE + 0x07;
int const TAGS_BASE_ALL_OR_NONE         = TAGS_BASE_PAGE + 0x08;
int const TAGS_BASE_RESERVED            = TAGS_BASE_PAGE + 0x09;
int const TAGS_BASE_BODY                = TAGS_BASE_PAGE + 0x0A;
int const TAGS_BASE_DATA                = TAGS_BASE_PAGE + 0x0B;
int const TAGS_BASE_ESTIMATED_DATA_SIZE = TAGS_BASE_PAGE + 0x0C;
int const TAGS_BASE_TRUNCATED           = TAGS_BASE_PAGE + 0x0D;
int const TAGS_BASE_ATTACHMENTS         = TAGS_BASE_PAGE + 0x0E;
int const TAGS_BASE_ATTACHMENT          = TAGS_BASE_PAGE + 0x0F;
int const TAGS_BASE_DISPLAY_NAME        = TAGS_BASE_PAGE + 0x10;
int const TAGS_BASE_FILE_REFERENCE      = TAGS_BASE_PAGE + 0x11;
int const TAGS_BASE_METHOD              = TAGS_BASE_PAGE + 0x12;
int const TAGS_BASE_CONTENT_ID          = TAGS_BASE_PAGE + 0x13;
int const TAGS_BASE_CONTENT_LOCATION    = TAGS_BASE_PAGE + 0x14;
int const TAGS_BASE_IS_INLINE           = TAGS_BASE_PAGE + 0x15;
int const TAGS_BASE_NATIVE_BODY_TYPE    = TAGS_BASE_PAGE + 0x16;
int const TAGS_BASE_CONTENT_TYPE        = TAGS_BASE_PAGE + 0x17;

int const TAGS_SETTINGS_PAGE = TAGS_SETTINGS << TAGS_PAGESHIFT;
int const TAGS_SETTINGS_SETTINGS                    = TAGS_SETTINGS_PAGE + 0x05;
int const TAGS_SETTINGS_STATUS                      = TAGS_SETTINGS_PAGE + 0x06;
int const TAGS_SETTINGS_GET                         = TAGS_SETTINGS_PAGE + 0x07;
int const TAGS_SETTINGS_SET                         = TAGS_SETTINGS_PAGE + 0x08;
int const TAGS_SETTINGS_OOF                         = TAGS_SETTINGS_PAGE + 0x09;
int const TAGS_SETTINGS_OOF_STATE                   = TAGS_SETTINGS_PAGE + 0x0A;
int const TAGS_SETTINGS_START_TIME                  = TAGS_SETTINGS_PAGE + 0x0B;
int const TAGS_SETTINGS_END_TIME                    = TAGS_SETTINGS_PAGE + 0x0C;
int const TAGS_SETTINGS_OOF_MESSAGE                 = TAGS_SETTINGS_PAGE + 0x0D;
int const TAGS_SETTINGS_APPLIES_TO_INTERNAL         = TAGS_SETTINGS_PAGE + 0x0E;
int const TAGS_SETTINGS_APPLIES_TO_EXTERNAL_KNOWN   = TAGS_SETTINGS_PAGE + 0x0F;
int const TAGS_SETTINGS_APPLIES_TO_EXTERNAL_UNKNOWN = TAGS_SETTINGS_PAGE + 0x10;
int const TAGS_SETTINGS_ENABLED                     = TAGS_SETTINGS_PAGE + 0x11;
int const TAGS_SETTINGS_REPLY_MESSAGE               = TAGS_SETTINGS_PAGE + 0x12;
int const TAGS_SETTINGS_BODY_TYPE                   = TAGS_SETTINGS_PAGE + 0x13;
int const TAGS_SETTINGS_DEVICE_PASSWORD             = TAGS_SETTINGS_PAGE + 0x14;
int const TAGS_SETTINGS_PASSWORD                    = TAGS_SETTINGS_PAGE + 0x15;
int const TAGS_SETTINGS_DEVICE_INFORMATION          = TAGS_SETTINGS_PAGE + 0x16;
int const TAGS_SETTINGS_MODEL                       = TAGS_SETTINGS_PAGE + 0x17;
int const TAGS_SETTINGS_IMEI                        = TAGS_SETTINGS_PAGE + 0x18;
int const TAGS_SETTINGS_FRIENDLY_NAME               = TAGS_SETTINGS_PAGE + 0x19;
int const TAGS_SETTINGS_OS                          = TAGS_SETTINGS_PAGE + 0x1A;
int const TAGS_SETTINGS_OS_LANGUAGE                 = TAGS_SETTINGS_PAGE + 0x1B;
int const TAGS_SETTINGS_PHONE_NUMBER                = TAGS_SETTINGS_PAGE + 0x1C;
int const TAGS_SETTINGS_USER_INFORMATION            = TAGS_SETTINGS_PAGE + 0x1D;
int const TAGS_SETTINGS_EMAIL_ADDRESS               = TAGS_SETTINGS_PAGE + 0x1E;
int const TAGS_SETTINGS_SMTP_ADDRESS                = TAGS_SETTINGS_PAGE + 0x1F;
int const TAGS_SETTINGS_USER_AGENT                  = TAGS_SETTINGS_PAGE + 0x20;
int const TAGS_SETTINGS_ENABLE_OUTGOING_SMS         = TAGS_SETTINGS_PAGE + 0x21;
int const TAGS_SETTINGS_MOBILE_OPERATOR             = TAGS_SETTINGS_PAGE + 0x22;

int const TAGS_ITEMS_PAGE = TAGS_ITEMS << TAGS_PAGESHIFT;
int const TAGS_ITEMS_ITEMS              = TAGS_ITEMS_PAGE + 0x05;
int const TAGS_ITEMS_FETCH              = TAGS_ITEMS_PAGE + 0x06;
int const TAGS_ITEMS_STORE              = TAGS_ITEMS_PAGE + 0x07;
int const TAGS_ITEMS_OPTIONS            = TAGS_ITEMS_PAGE + 0x08;
int const TAGS_ITEMS_RANGE              = TAGS_ITEMS_PAGE + 0x09;
int const TAGS_ITEMS_TOTAL              = TAGS_ITEMS_PAGE + 0x0A;
int const TAGS_ITEMS_PROPERTIES         = TAGS_ITEMS_PAGE + 0x0B;
int const TAGS_ITEMS_DATA               = TAGS_ITEMS_PAGE + 0x0C;
int const TAGS_ITEMS_STATUS             = TAGS_ITEMS_PAGE + 0x0D;
int const TAGS_ITEMS_RESPONSE           = TAGS_ITEMS_PAGE + 0x0E;
int const TAGS_ITEMS_VERSION            = TAGS_ITEMS_PAGE + 0x0F;
int const TAGS_ITEMS_SCHEMA             = TAGS_ITEMS_PAGE + 0x10;
int const TAGS_ITEMS_PART               = TAGS_ITEMS_PAGE + 0x11;
int const TAGS_ITEMS_EMPTY_FOLDER       = TAGS_ITEMS_PAGE + 0x12;
int const TAGS_ITEMS_DELETE_SUB_FOLDERS = TAGS_ITEMS_PAGE + 0x13;
int const TAGS_ITEMS_USERNAME           = TAGS_ITEMS_PAGE + 0x14;
int const TAGS_ITEMS_PASSWORD           = TAGS_ITEMS_PAGE + 0x15;
int const TAGS_ITEMS_MOVE               = TAGS_ITEMS_PAGE + 0x16;
int const TAGS_ITEMS_DSTFLDID           = TAGS_ITEMS_PAGE + 0x17;
int const TAGS_ITEMS_CONVERSATION_ID    = TAGS_ITEMS_PAGE + 0x18;
int const TAGS_ITEMS_MOVE_ALWAYS        = TAGS_ITEMS_PAGE + 0x19;

int const TAGS_COMPOSE_PAGE = TAGS_COMPOSE << TAGS_PAGESHIFT;
int const TAGS_COMPOSE_SEND_MAIL            = TAGS_COMPOSE_PAGE + 0x05;
int const TAGS_COMPOSE_SMART_FORWARD        = TAGS_COMPOSE_PAGE + 0x06;
int const TAGS_COMPOSE_SMART_REPLY          = TAGS_COMPOSE_PAGE + 0x07;
int const TAGS_COMPOSE_SAVE_IN_SENT_ITEMS   = TAGS_COMPOSE_PAGE + 0x08;
int const TAGS_COMPOSE_REPLACE_MIME         = TAGS_COMPOSE_PAGE + 0x09;
// There is no tag for COMPOSE_PAGE + 0x0A
int const TAGS_COMPOSE_SOURCE               = TAGS_COMPOSE_PAGE + 0x0B;
int const TAGS_COMPOSE_FOLDER_ID            = TAGS_COMPOSE_PAGE + 0x0C;
int const TAGS_COMPOSE_ITEM_ID              = TAGS_COMPOSE_PAGE + 0x0D;
int const TAGS_COMPOSE_LONG_ID              = TAGS_COMPOSE_PAGE + 0x0E;
int const TAGS_COMPOSE_INSTANCE_ID          = TAGS_COMPOSE_PAGE + 0x0F;
int const TAGS_COMPOSE_MIME                 = TAGS_COMPOSE_PAGE + 0x10;
int const TAGS_COMPOSE_CLIENT_ID            = TAGS_COMPOSE_PAGE + 0x11;
int const TAGS_COMPOSE_STATUS               = TAGS_COMPOSE_PAGE + 0x12;
int const TAGS_COMPOSE_ACCOUNT_ID           = TAGS_COMPOSE_PAGE + 0x13;

int const TAGS_EMAIL2_PAGE = TAGS_EMAIL2 << TAGS_PAGESHIFT;
int const TAGS_EMAIL2_UM_CALLER_ID              = TAGS_EMAIL2_PAGE + 0x05;
int const TAGS_EMAIL2_UM_USER_NOTES             = TAGS_EMAIL2_PAGE + 0x06;
int const TAGS_EMAIL2_UM_ATT_DURATION           = TAGS_EMAIL2_PAGE + 0x07;
int const TAGS_EMAIL2_UM_ATT_ORDER              = TAGS_EMAIL2_PAGE + 0x08;
int const TAGS_EMAIL2_CONVERSATION_ID           = TAGS_EMAIL2_PAGE + 0x09;
int const TAGS_EMAIL2_CONVERSATION_INDEX        = TAGS_EMAIL2_PAGE + 0x0A;
int const TAGS_EMAIL2_LAST_VERB_EXECUTED        = TAGS_EMAIL2_PAGE + 0x0B;
int const TAGS_EMAIL2_LAST_VERB_EXECUTION_TIME  = TAGS_EMAIL2_PAGE + 0x0C;
int const TAGS_EMAIL2_RECEIVED_AS_BCC           = TAGS_EMAIL2_PAGE + 0x0D;
int const TAGS_EMAIL2_SENDER                    = TAGS_EMAIL2_PAGE + 0x0E;
int const TAGS_EMAIL2_CALENDAR_TYPE             = TAGS_EMAIL2_PAGE + 0x0F;
int const TAGS_EMAIL2_IS_LEAP_MONTH             = TAGS_EMAIL2_PAGE + 0x10;
int const TAGS_EMAIL2_ACCOUNT_ID                = TAGS_EMAIL2_PAGE + 0x11;
int const TAGS_EMAIL2_FIRST_DAY_OF_WEEK         = TAGS_EMAIL2_PAGE + 0x12;
int const TAGS_EMAIL2_MEETING_MESSAGE_TYPE      = TAGS_EMAIL2_PAGE + 0x13;

int const TAGS_RIGHTS_PAGE = TAGS_RIGHTS << TAGS_PAGESHIFT;
int const TAGS_RIGHTS_SUPPORT                       = TAGS_RIGHTS_PAGE + 0x05;
int const TAGS_RIGHTS_TEMPLATES                     = TAGS_RIGHTS_PAGE + 0x06;
int const TAGS_RIGHTS_TEMPLATE                      = TAGS_RIGHTS_PAGE + 0x07;
int const TAGS_RIGHTS_LICENSE                       = TAGS_RIGHTS_PAGE + 0x08;
int const TAGS_RIGHTS_EDIT_ALLOWED                  = TAGS_RIGHTS_PAGE + 0x09;
int const TAGS_RIGHTS_REPLY_ALLOWED                 = TAGS_RIGHTS_PAGE + 0x0A;
int const TAGS_RIGHTS_REPLY_ALL_ALLOWED             = TAGS_RIGHTS_PAGE + 0x0B;
int const TAGS_RIGHTS_FORWARD_ALLOWED               = TAGS_RIGHTS_PAGE + 0x0C;
int const TAGS_RIGHTS_MODIFY_RECIPIENTS_ALLOWED     = TAGS_RIGHTS_PAGE + 0x0D;
int const TAGS_RIGHTS_EXTRACT_ALLOWED               = TAGS_RIGHTS_PAGE + 0x0E;
int const TAGS_RIGHTS_PRINT_ALLOWED                 = TAGS_RIGHTS_PAGE + 0x0F;
int const TAGS_RIGHTS_EXPORT_ALLOWED                = TAGS_RIGHTS_PAGE + 0x10;
int const TAGS_RIGHTS_PROGRAMMATIC_ACCESS_ALLOWED   = TAGS_RIGHTS_PAGE + 0x11;
int const TAGS_RIGHTS_OWNER                         = TAGS_RIGHTS_PAGE + 0x12;
int const TAGS_RIGHTS_CONTENT_EXPIRY_DATE           = TAGS_RIGHTS_PAGE + 0x13;
int const TAGS_RIGHTS_TEMPLATE_ID                   = TAGS_RIGHTS_PAGE + 0x14;
int const TAGS_RIGHTS_TEMPLATE_NAME                 = TAGS_RIGHTS_PAGE + 0x15;
int const TAGS_RIGHTS_TEMPLATE_DESCRIPTION          = TAGS_RIGHTS_PAGE + 0x16;
int const TAGS_RIGHTS_CONTENT_OWNER                 = TAGS_RIGHTS_PAGE + 0x17;
int const TAGS_RIGHTS_REMOVE_RM_DISTRIBUTION        = TAGS_RIGHTS_PAGE + 0x18;

@end
